version: '3.3'

services:
    app:
        image: roseth/simplezat:stable
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        command: sh -c "./entrypoint.dev.sh"
