version: '3.3'

services:
    nginx: 
        image: roseth/simplezat-nginx:stable
        ports:
            - "8000:80"
        volumes:
            - app-staticfiles:/app/static
        depends-on:
            - app
    db:
        image: postgres:11.1-alpine
        volumes:
            - postgres-data:/var/lib/postgressql/data
    app:
        image: roseth/simplezat:stable
        volumes:
            - app-staticfiles:/app/static
        command: sh -c "./entrypoint.dev.sh"
        depends-on:
            - db

volumes:
    postgres-data:
    app-staticfiles:
