version: '3.7'

services:
    app:
        image: roseth/simplezat:unstable
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        command: sh -c "./entrypoint.sh"
