version: '3.3'

services:
    db:
        image: postgres:11.1-alpine
        volumes:
            - postgres-data:/var/lib/postgressql/data
    app:
        image: roseth/simplezat:live
        ports:
            - "8000:8000"
        command: sh -c "./entrypoint.dev.sh"

volumes:
    postgres-data:
