version: 2
jobs:
  checkout_code:
    working_directory: ~/Django-Tdd-simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    working_directory: ~/Django-Tdd-simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pip3 install pipenv 
    
  static_analysis:
    working_directory: ~/Django-Tdd-simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pipenv install --dev
            pipenv run flake8

  unit_tests:
    working_directory: ~/Django-Tdd-simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pipenv install --dev
            cd simplezat
            pipenv run python manage.py test

  deploy:
    working_directory: ~/Django-Tdd-simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Stable Images
          command: |
            docker build -t roseth/simplezat:stable -f Dockerfile.dev . 
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push roseth/simplezat:stable
      - add_ssh_keys:
          fingerprints:
            - "38:6b:7d:25:ad:ba:05:49:52:88:75:60:5a:b6:e4:22"
      - run:
          name: Install Dependencies
          command: |
            cd deployment
            pipenv install ansible
            pipenv run ansible-playbook -i hosts playbooks/dev.yml --extra-vars "project_root=~/simplezat"


workflows:
  version: 2
  simplezat_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_analysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy:
          requires:
            - unit_tests
